databases:
  - name: dolmed_db
    databaseName: dolmed_production
    user: dolmed_user
    plan: free

services:
  - type: web
    name: dolmed
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dolmed_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
